"""all_tables

Revision ID: 4dbd6357e2bc
Revises: 9d09e1cb9b76
Create Date: 2024-12-07 20:03:48.299323

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '4dbd6357e2bc'
down_revision = '9d09e1cb9b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking',
    sa.Column('id_sposob', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('per_kkal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_sposob'),
    schema='my_app_schema'
    )
    op.create_table('ingredients',
    sa.Column('id_ingredient', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ed_izm', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id_ingredient'),
    schema='my_app_schema'
    )
    op.create_table('users',
    sa.Column('surname', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('firstname', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('fathername', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('id_username', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('country', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id_username'),
    schema='my_app_schema'
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_country', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id_meal', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id_meal'], ['my_app_schema.meals.id_meal'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='my_app_schema'
    )
    op.create_table('feedback',
    sa.Column('id_coment', sa.Integer(), nullable=False),
    sa.Column('id_meal', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id_username', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('coment', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('dat', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_meal'], ['my_app_schema.meals.id_meal'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_username'], ['my_app_schema.users.id_username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_coment'),
    schema='my_app_schema'
    )
    op.create_table('kbzu',
    sa.Column('id_kbzu', sa.Integer(), nullable=False),
    sa.Column('id_ingredient', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('belki', sa.Float(), nullable=False),
    sa.Column('zhiri', sa.Float(), nullable=False),
    sa.Column('uglevodi', sa.Float(), nullable=False),
    sa.Column('kkal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_ingredient'], ['my_app_schema.ingredients.id_ingredient'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_kbzu'),
    schema='my_app_schema'
    )
    op.create_table('sostav',
    sa.Column('id_sostav', sa.Integer(), nullable=False),
    sa.Column('id_meal', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id_ingredient', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('cnt', sa.Integer(), nullable=False),
    sa.Column('ed_izm', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id_sposob', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['id_ingredient'], ['my_app_schema.ingredients.id_ingredient'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_meal'], ['my_app_schema.meals.id_meal'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sposob'], ['my_app_schema.cooking.id_sposob'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sostav'),
    schema='my_app_schema'
    )
    op.create_table('vostreb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_username', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('id_meal', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('count_obr', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_meal'], ['my_app_schema.meals.id_meal'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_username'], ['my_app_schema.users.id_username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='my_app_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vostreb', schema='my_app_schema')
    op.drop_table('sostav', schema='my_app_schema')
    op.drop_table('kbzu', schema='my_app_schema')
    op.drop_table('feedback', schema='my_app_schema')
    op.drop_table('country', schema='my_app_schema')
    op.drop_table('users', schema='my_app_schema')
    op.drop_table('ingredients', schema='my_app_schema')
    op.drop_table('cooking', schema='my_app_schema')
    # ### end Alembic commands ###
